"""empty message

Revision ID: 31f42b7a560e
Revises: None
Create Date: 2015-08-30 12:21:48.199479

"""

# revision identifiers, used by Alembic.
revision = '31f42b7a560e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
